### ISSUE TITLE
BootstrapManager::readSPIFFS does not work correctly when called several times

### ISSUE THREAD

**Issue by Pronoe** [sblantipodi/arduino_bootstrapper#12]
Hi Davide,

I am using `writeToSPIFFS` and `readSPIFFS `to manage a json file for context saving (containing information such as total running time).
Initial reading at startup was working fine, as it was for the setup file `setup.json`.
Then during testing I have noticed that the repeated reading of the context file every 10 mins for debugging purposes was returning a json doc containing null information.

You have raised a similar [issue](https://github.com/bblanchon/ArduinoJson/issues/1260)  in 2020 for the ArduinoJson library but this issue has been closed with the following comment:
> _I am trying to read/write SPIFFS in the ESP8266, it seems that closing the file before returning the DynamicJsonDocument solved the problem when reading._

After reviewing your code, I noticed that for the specific code for the ESP32, the `file.close` statement was missing as well as the initial declaration `DynamicJsonDocument jsonDoc(1024);`

However, adding these 2 statements did not fix the issue.
After additional research, I have found this [issue](https://github.com/bblanchon/ArduinoJson/issues/780) that looks similar.

The final comment for this issue is:

> bblanchon commented on 21 Jul 2018
> By passing a char[] to deserializeJson(), you triggered the zero-copy mode of ArduinoJson.
> In this mode, ArduinoJson stores pointers to the input buffer instead of making copies.
> To fix this program, you need to disable the zero-copy mode by passing a read-only input; to do that, simply cast the input to a const char*: DeserializationError error = deserializeJson(_InputDoc, (const char*)json);
> ``

I then applied this solution to the ESP32 code: 
```
DeserializationError deserializeError = deserializeJson(jsonDoc, (const char*)buf.get());
```
and now the function is working as expected.

Regards
Patrick

**Comment by sblantipodi** [comment]
Hi Pronoe, you have discovered the issue and fixed it...
I'll just follow your suggestion after some no regression tests but it should work...

Fix will be in the next release.

Thank you very much.
Davide
