### ISSUE TITLE
Long blocking delays inside readSPIFFS and readLittleFS functions 

### ISSUE THREAD

**Issue by Pronoe** [sblantipodi/arduino_bootstrapper#13]
Hi Davide,
sorry for opening again an issue, I have another question.
In `BootstrapManager::readSPIFFS` you have a delay of 4 seconds at the end of the function and in `BootstrapManager::readLittleFS` you have a delay of 2 seconds.
What is the justification of such long delays ?
Probably this is to give time to your smart display to refresh, but if this is the case, you should better displace this delay inside the `Helpers::smartDisplay()` function.

At the moment, the main loop of my code reads a context file every 10 minutes, and this 4 s delay blocks any other operation during 4 s . For example, the blinking of the built-in Led is stopped during 4 s every 10 minutes.
This is not really serious for my project but this could be an issue for some other time critical applications for other users.

**Comment by sblantipodi** [comment]
no need to sorry, I thank you for all the good ideas.
it will be fixed in the next release, thank you again @Pronoe, really appreciated.
