### ISSUE TITLE
uMQTT library

### ISSUE THREAD

**Issue by happytm** [sblantipodi/arduino_bootstrapper#2]
I think this is perfect bootstrap library for ESP projects. Is it possible to include uMQTT or TinyMqtt broker linked below ?

https://github.com/martin-ger/uMQTTBroker 

or

https://github.com/hsaturn/TinyMqtt

Thanks.

**Comment by sblantipodi** [comment]
@happytm Hi, sorry for the late reply, for some strange reasons I haven't seen this issue before.

Can you tell me why you prefer those libs over the pubsubclient used by Arduino Bootstrapper?

Thanks
