### ISSUE TITLE
Always running webserver for Improv branch

### ISSUE THREAD

**Issue by PaulWieland** [sblantipodi/arduino_bootstrapper#25]
I'm experimenting with the improv branch of this library, and it seems to be almost perfect for what I need it to do. The only thing missing is that the webserver which allows the user to configure MQTT (and other params) isn't always running, therefore the "Visit Device" button in the Improv web UI doesn't work. It also doesn't pre populate the saved values in the webform - I assume because the device config was originally intended to be one time use only.

What are your thoughts on this? Do you plan to continue the improv development and include it in the main branch? Do you want me to submit a pull request that enables the web server when improv is enabled?

Either way, nice work. This is library is going to work really well for my project.

**Comment by sblantipodi** [comment]
Hi @PaulWieland, sorry for the late reply.
The current version of the lib supports improv, I use this lib on the Luciferin project and it seems to work well in that implementation.

If you want to leave the webserver always running you need to use the `forceWebServer` param.

This feature has been recently added by @Pronoe
