### ISSUE TITLE
Superfluous display reference

### ISSUE THREAD

**Issue by Reneg973** [sblantipodi/arduino_bootstrapper#3]
Hi there,
nice project. But could you please remove the hardcoded reference to the display?
+ LED_BUILTIN: undeclared identifier used in nonblokingBlink

**Comment by Reneg973** [comment]
Hi, du you think it will be possible to do this or do you prefer that I clone your repo and do it on my own?

**Comment by sblantipodi** [comment]
Hi, sorry for the late reply, I'm very busy this days.
What do you want to remove exactly? in what file?

if you think that there is something that can be useful to everyone, you can open a pull request and I can merge it into the main branch. thanks!

**Comment by Reneg973** [comment]
Well first I have a system without a LED_BUILTIN. Second I don't have that display you are using with the graphics library. This output is not required to work with your library. So it should be optional.
What do you think? I am also a little bit busy. Would like to use this bootstrapper with my esp-01s.
Ok will try to make a PR
