### ISSUE TITLE
Memory footprint?

### ISSUE THREAD

**Issue by Reneg973** [sblantipodi/arduino_bootstrapper#4]
I've used this library together with the serial example for ESP32 project (only serial communication). Before adding it sketch size was 257kB, now it is 968kB. I am not sure the memory left is enough for the devices I want to add.

**Comment by sblantipodi** [comment]
@Reneg973 ESP32 has plenty of memory, even ESP8266 runs this lib no problem. Memory optimization is something that will come later.

Thanks for your interest. Closing the issue but feel free to reply if you want.
